version: "3.3"
services: 
  rtmp: 
    build: ./rtmp
    ports: 
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes: 
      - ./temp:/tmp/hls
  auth: 
    build: ./authentication
    container_name: auth_server 